Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /accounts/login/ HTTP/1.1" 200 4039
"GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 124962
"GET /static/styles/login_main.css HTTP/1.1" 200 10314
"GET /static/styles/util.css HTTP/1.1" 200 86794
"GET /static/images/logo.png HTTP/1.1" 200 24694
"GET /static/iconic/css/material-design-iconic-font.min.css HTTP/1.1" 200 70815
"GET /static/images/bg-01.jpg HTTP/1.1" 200 2846166
"GET /static/iconic/fonts/Material-Design-Iconic-Font.woff2?v=2.2.0 HTTP/1.1" 200 38384
"GET /static/fonts/poppins/Poppins-Medium.ttf HTTP/1.1" 200 143516
"GET /static/fonts/poppins/Poppins-SemiBold.ttf HTTP/1.1" 200 142148
"GET /static/fonts/poppins/Poppins-Regular.ttf HTTP/1.1" 200 145312
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2566
"GET / HTTP/1.1" 302 0
"GET /accounts/login/ HTTP/1.1" 200 4039
"GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 124962
"GET /static/styles/login_main.css HTTP/1.1" 200 10314
"GET /static/styles/util.css HTTP/1.1" 200 86794
"GET /static/images/logo.png HTTP/1.1" 200 24694
"GET /static/iconic/css/material-design-iconic-font.min.css HTTP/1.1" 200 70815
"GET /static/images/bg-01.jpg HTTP/1.1" 200 2846166
"GET /static/iconic/fonts/Material-Design-Iconic-Font.woff2?v=2.2.0 HTTP/1.1" 200 38384
"GET /static/fonts/poppins/Poppins-SemiBold.ttf HTTP/1.1" 200 142148
"GET /static/fonts/poppins/Poppins-Medium.ttf HTTP/1.1" 200 143516
"GET /static/fonts/poppins/Poppins-Regular.ttf HTTP/1.1" 200 145312
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2566
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /core/home/ HTTP/1.1" 200 6664
"GET /static/styles/main.css HTTP/1.1" 200 12332
"GET /static/images/account.png HTTP/1.1" 200 22593
"GET /static/js/slide_bar.js HTTP/1.1" 200 176
"GET /core/doctor/manage_diagnosis/ HTTP/1.1" 200 6968
"GET /static/js/diagnosis_management.js HTTP/1.1" 200 7844
"GET /core/load_medical_histories/ HTTP/1.1" 200 762
"GET /core/create-prescription/1/ HTTP/1.1" 200 7307
Created prescription: 5
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Error in generate_pdf: module 'appointment_management.settings' has no attribute 'STATIC_ROOT'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 82, in generate_pdf
    settings.STATIC_ROOT) if settings.STATIC_ROOT else None
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'appointment_management.settings' has no attribute 'STATIC_ROOT'
PDF generation error: Error generating PDF: module 'appointment_management.settings' has no attribute 'STATIC_ROOT'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 82, in generate_pdf
    settings.STATIC_ROOT) if settings.STATIC_ROOT else None
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'appointment_management.settings' has no attribute 'STATIC_ROOT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\views\prescription_views.py", line 51, in create_prescription
    pdf = generate_pdf(
          ^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 100, in generate_pdf
    raise Exception(f"Error generating PDF: {str(e)}")
Exception: Error generating PDF: module 'appointment_management.settings' has no attribute 'STATIC_ROOT'
"POST /core/create-prescription/1/ HTTP/1.1" 200 7856
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET /accounts/login/ HTTP/1.1" 200 4039
"GET / HTTP/1.1" 302 0
"GET /accounts/login/ HTTP/1.1" 200 4039
"GET /static/styles/login_main.css HTTP/1.1" 200 10314
"GET /static/styles/util.css HTTP/1.1" 200 86794
"GET /static/images/logo.png HTTP/1.1" 200 24694
"GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 124962
"GET /static/iconic/css/material-design-iconic-font.min.css HTTP/1.1" 200 70815
"GET /static/images/bg-01.jpg HTTP/1.1" 200 2846166
"GET /static/iconic/fonts/Material-Design-Iconic-Font.woff2?v=2.2.0 HTTP/1.1" 200 38384
"GET /static/fonts/poppins/Poppins-Regular.ttf HTTP/1.1" 200 145312
"GET /static/fonts/poppins/Poppins-Medium.ttf HTTP/1.1" 200 143516
"GET /static/fonts/poppins/Poppins-SemiBold.ttf HTTP/1.1" 200 142148
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2693
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /core/home/ HTTP/1.1" 200 6664
"GET /static/styles/main.css HTTP/1.1" 200 12332
"GET /static/images/account.png HTTP/1.1" 200 22593
"GET /static/js/slide_bar.js HTTP/1.1" 200 176
"GET /core/doctor/manage_diagnosis/ HTTP/1.1" 200 6968
"GET /static/js/diagnosis_management.js HTTP/1.1" 200 7844
"GET /core/load_medical_histories/ HTTP/1.1" 200 762
"GET /core/create-prescription/1/ HTTP/1.1" 200 7307
Created prescription: 6
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Using base URL: file://C:\Users\Rodrigo\Desktop\appointment_management
Created prescription: 7
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Using base URL: file:///C:/Users/Rodrigo/Desktop/appointment_management/core/static
WeasyPrint error: PDF.__init__() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 92, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\document.py", line 399, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\pdf\__init__.py", line 127, in generate_pdf
    pdf = pydyf.PDF((version or '1.7'), identifier)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PDF.__init__() takes 1 positional argument but 3 were given
Error in generate_pdf: PDF.__init__() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 92, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\document.py", line 399, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\pdf\__init__.py", line 127, in generate_pdf
    pdf = pydyf.PDF((version or '1.7'), identifier)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PDF.__init__() takes 1 positional argument but 3 were given
PDF generation error: Error generating PDF: PDF.__init__() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 92, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\document.py", line 399, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\weasyprint\pdf\__init__.py", line 127, in generate_pdf
    pdf = pydyf.PDF((version or '1.7'), identifier)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PDF.__init__() takes 1 positional argument but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\views\prescription_views.py", line 51, in create_prescription
    pdf = generate_pdf(
          ^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 104, in generate_pdf
    raise Exception(f"Error generating PDF: {str(e)}")
Exception: Error generating PDF: PDF.__init__() takes 1 positional argument but 3 were given
Created prescription: 8
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Using base URL: file:///C:/Users/Rodrigo/Desktop/appointment_management/core/static
PDF generated successfully
PDF generated, saving file
PDF saved successfully
PDF generation error: Reverse for 'manage_diagnosis' with keyword arguments '{'medical_history_id': 1}' not found. 1 pattern(s) tried: ['core/doctor/manage_diagnosis/\\Z']
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\views\prescription_views.py", line 61, in create_prescription
    return redirect('manage_diagnosis', medical_history_id=medical_history.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'manage_diagnosis' with keyword arguments '{'medical_history_id': 1}' not found. 1 pattern(s) tried: ['core/doctor/manage_diagnosis/\\Z']
Created prescription: 9
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Using base URL: file:///C:/Users/Rodrigo/Desktop/appointment_management/core/static
PDF generated successfully
PDF generated, saving file
PDF saved successfully
Created prescription: 10
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Using base URL: file:///C:/Users/Rodrigo/Desktop/appointment_management/core/static
WeasyPrint error: HTML.write_pdf() got an unexpected keyword argument 'optimize_size'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 88, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
TypeError: HTML.write_pdf() got an unexpected keyword argument 'optimize_size'
Error in generate_pdf: HTML.write_pdf() got an unexpected keyword argument 'optimize_size'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 88, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
TypeError: HTML.write_pdf() got an unexpected keyword argument 'optimize_size'
PDF generation error: Error generating PDF: HTML.write_pdf() got an unexpected keyword argument 'optimize_size'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 88, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
TypeError: HTML.write_pdf() got an unexpected keyword argument 'optimize_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\views\prescription_views.py", line 51, in create_prescription
    pdf = generate_pdf(
          ^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 109, in generate_pdf
    raise Exception(f"Error generating PDF: {str(e)}")
Exception: Error generating PDF: HTML.write_pdf() got an unexpected keyword argument 'optimize_size'
Created prescription: 11
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Using base URL: file:///C:/Users/Rodrigo/Desktop/appointment_management/core/static
WeasyPrint error: HTML.write_pdf() got an unexpected keyword argument 'metadata'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 88, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
TypeError: HTML.write_pdf() got an unexpected keyword argument 'metadata'
Error in generate_pdf: HTML.write_pdf() got an unexpected keyword argument 'metadata'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 88, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
TypeError: HTML.write_pdf() got an unexpected keyword argument 'metadata'
PDF generation error: Error generating PDF: HTML.write_pdf() got an unexpected keyword argument 'metadata'
Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 88, in generate_pdf
    ).write_pdf(
      ^^^^^^^^^^
TypeError: HTML.write_pdf() got an unexpected keyword argument 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\views\prescription_views.py", line 51, in create_prescription
    pdf = generate_pdf(
          ^^^^^^^^^^^^^
  File "C:\Users\Rodrigo\Desktop\appointment_management\core\utils.py", line 105, in generate_pdf
    raise Exception(f"Error generating PDF: {str(e)}")
Exception: Error generating PDF: HTML.write_pdf() got an unexpected keyword argument 'metadata'
Created prescription: 12
Starting PDF generation
Generating PDF from template: C:\Users\Rodrigo\Desktop\appointment_management\core/templates\doctor/prescription_template.html
Template rendered successfully
Using base URL: file:///C:/Users/Rodrigo/Desktop/appointment_management/core/static
PDF generated successfully
PDF generated, saving file
PDF saved successfully
